vich_uploader:
  db_driver: orm

  mappings:
    avatar:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    agreement:
        uri_prefix: /uploads/agreements
        upload_destination: '%kernel.project_dir%/public/uploads/agreements'
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true